version: '3'
services:
  database:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
volumes:
  mongodb_data:
